version: '3.8'

services:
  node:
    build: .
    container_name: apple-music-api_node
    environment:
      YARN_CACHE_FOLDER: /workspace/.yarn/cache
    stdin_open: true
    volumes:
      - ./:/workspace:cached
      - ./.yarn/cache:/workspace/.yarn/cache:delegated
      - ./node_modules:/workspace/node_modules:delegated

    working_dir: /workspace

networks:
  default:
